version: '3.8'
services:
   app:
     build: .
     ports:
       - "8080:8080"
     environment :
       - SPRING_PROFILES_ACTIVE=dev
       - MONGODB_URI=mongodb://mongo:27017/twitterclone
       - SPRING_DATA_REDIS_HOST=redis
       - SPRING_DATA_REDIS_PORT=6379
     depends_on:
       - mongo
       - redis

   mongo:
     image: mongo:latest
     restart: always
     ports:
       - "27017:27017"

   redis :
     image : redis:7.2.5
     container_name : twitterclone_redis
     ports :
       - "6379:6379"

   prometheus :
     image : prom/prometheus
     ports :
       - "9090:9090"
     volumes :
       - ./prometheus.yml:/etc/prometheus/prometheus.yml
     command :
       - '--config.file=/etc/prometheus/prometheus.yml'
   grafana :
     image : grafana/grafana
     ports :
       - "3000:3000"
