name: Build and Publish to GHCR

on:
  push:
    branches:
      - main
  pull_request :
    branches :
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
#        with:
#          fetch-depth: '0' # Get full history for better caching

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name : Cache Gradle dependencies
        uses : actions/cache@v2
        with :
          path : ~/.gradle/caches
          key : ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys : |
            ${{ runner.os }}-gradle-

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "persey86" --password-stdin

        # Install dependencies and build image
      - name: Build Docker image
        run: ./gradlew bootBuildImage --imageName=ghcr.io/${{ github.repository_owner }}/twitter-clone:latest

      # Login to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push the Docker image to GHCR
      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/twitter-clone:latest
