name: Build and Publish Docker Image to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0' # Get full history for better caching

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      # Log in to GHCR
      - name : Log in to GitHub Container Registry
        run : |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "persey86" --password-stdin

      - name: Build and publish Docker image
        run: |
          # Build the Docker image
          docker build -t ghcr.io/${{ github.repository }}/twitter-clone:latest .
          # Push the Docker image to GHCR
          docker push ghcr.io/${{ github.repository }}/twitter-clone:latest
